name: Publish Release Packages

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run dist
      - run: npm pack
      - name: Upload Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            masked-interface.zip
            directus-extension-masked-interface*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
